import json
import tempfile
from pathlib import Path
import httpx
from PIL import Image
from novel_manga.config import Settings
from novel_manga.providers.base import ImageResult
from novel_manga.providers.phanrouter import PhanRouterMediaProvider


def test_local_h3_reference_voice_reaches_the_video_request(tmp_path):
    import base64
    from novel_manga.providers.local_h3 import LocalH3MediaProvider

    voice = tmp_path / 'reference.wav'
    voice.write_bytes(b'RIFF-fixed-reference-audio')
    provider = LocalH3MediaProvider(Settings(video_model='minimax-h3-ref2va-turbo'), 'http://h3.invalid')
    calls = []
    def handle(request):
        if request.method == 'POST':
            calls.append(json.loads(request.content))
            return httpx.Response(200, json={'id': 'voice-reference-task'})
        if request.url.path.endswith('/content'):
            return httpx.Response(200, content=b'generated-video')
        return httpx.Response(200, json={'status': 'completed'})
    provider.h3_client.close()
    provider.h3_client = httpx.Client(transport=httpx.MockTransport(handle), trust_env=False)
    try:
        output = tmp_path / 'clip.mp4'
        provider.create_video('A person speaks.', None, output, 6, reference_audios=(voice,))
        assert output.read_bytes() == b'generated-video'
        condition, = calls[0]['conditions']
        assert condition['type'] == 'audio' and condition['role'] == 'reference'
        assert condition['uri'].startswith('data:audio/wav;base64,')
        assert base64.b64decode(condition['uri'].split(',', 1)[1]) == voice.read_bytes()
    finally:
        provider.client.close()
        provider.h3_client.close()


def frozen_providers():
    results={}
    for model in ['doubao-seedance-2-0','doubao-seedance-2-5','MiniMax-H3','image','doubao-seedream-5.0-lite']:
     with tempfile.TemporaryDirectory(prefix='nmv-provider-freeze-') as tmp:
      base=Path(tmp);reference=base/'reference.jpeg';Image.new('RGB',(64,96),'blue').save(reference)
      audio=base/'voice.wav';audio.write_bytes(b'fixed mocked reference audio')
      calls=[]
      def handle(request):
       calls.append({'method':request.method,'url':str(request.url),'body':json.loads(request.content) if request.content else None})
       if request.url.host=='cdn.invalid':return httpx.Response(200,content=b'fixed generated bytes')
       if request.method=='POST':
        if '/v1/images/generations' in request.url.path:return httpx.Response(200,json={'data':[{'url':'http://cdn.invalid/image.jpeg'}]})
        return httpx.Response(200,json={'task_id':'fixed-task'})
       return httpx.Response(200,json={'data':{'status':'succeeded','url':'http://cdn.invalid/result.mp4','usage':{'tokens':123}}})
      settings=Settings(phanrouter_base_url='http://api.invalid',phanrouter_api_key='test-only',video_model=model,
        image_model='doubao-seedream-5.0-lite' if model.startswith('doubao-seedream') else 'image-test',inline_reference_images=True)
      p=PhanRouterMediaProvider(settings);p.client.close();p.client=httpx.Client(transport=httpx.MockTransport(handle),trust_env=False)
      if model in {'image','doubao-seedream-5.0-lite'}:
       p.create_image('角色画像',base/'image.jpeg',reference=reference)
      else:
       for _ in range(2):p.create_video('角色开门',ImageResult(path=reference,public_url='http://reference.invalid/card.jpeg'),base/'video.mp4',22,reference_audios=(audio,))
      records={f.name:json.loads(f.read_text()) for f in sorted(base.glob('*.json'))}
      results[model]={'requests':calls,'records':records}
      p.client.close()
    return results


def test_requests_resumed_tasks_and_usage_match_previous_provider():
    expected = json.loads((Path(__file__).parent / 'fixtures/provider_services_before.json').read_text())
    assert frozen_providers() == expected


def test_download_can_use_the_h3_direct_client_without_the_generation_client(tmp_path):
    generation_calls, download_calls = [], []
    def wrong(request):
        generation_calls.append(str(request.url))
        raise AssertionError('download went through the generation client')
    def retrieve(request):
        download_calls.append(str(request.url))
        return httpx.Response(200, content=b'existing paid artifact')
    provider = PhanRouterMediaProvider(Settings())
    provider.client.close()
    with httpx.Client(transport=httpx.MockTransport(wrong)) as generation, httpx.Client(transport=httpx.MockTransport(retrieve)) as direct:
        provider.client = generation
        path = tmp_path / 'clip.mp4'
        provider._download('http://internal.invalid/clip', path, client=direct)
    assert not generation_calls and download_calls == ['http://internal.invalid/clip']
    assert path.read_bytes() == b'existing paid artifact'
    assert not path.with_suffix('.mp4.partial').exists()
