import json
import tempfile
from pathlib import Path
import httpx
from PIL import Image
from novel_manga.config import Settings
from novel_manga.providers.base import ImageResult
from novel_manga.providers.phanrouter import PhanRouterMediaProvider


def test_local_h3_reference_voice_reaches_the_video_request(tmp_path):
    import base64
    from novel_manga.providers.local_h3 import LocalH3MediaProvider

    voice = tmp_path / 'reference.wav'
    voice.write_bytes(b'RIFF-fixed-reference-audio')
    provider = LocalH3MediaProvider(Settings(video_model='minimax-h3-ref2va-turbo'), 'http://h3.invalid')
    calls = []
    def handle(request):
        if request.method == 'POST':
            calls.append(json.loads(request.content))
            return httpx.Response(200, json={'id': 'voice-reference-task'})
        if request.url.path.endswith('/content'):
            return httpx.Response(200, content=b'generated-video')
        return httpx.Response(200, json={'status': 'completed'})
    provider.h3_client.close()
    provider.h3_client = httpx.Client(transport=httpx.MockTransport(handle), trust_env=False)
    try:
        output = tmp_path / 'clip.mp4'
        provider.create_video('A person speaks.', None, output, 6, reference_audios=(voice,))
        assert output.read_bytes() == b'generated-video'
        condition, = calls[0]['conditions']
        assert condition['type'] == 'audio' and condition['role'] == 'reference'
        assert condition['uri'].startswith('data:audio/wav;base64,')
        assert base64.b64decode(condition['uri'].split(',', 1)[1]) == voice.read_bytes()
    finally:
        provider.client.close()
        provider.h3_client.close()


def frozen_providers():
    results={}
    for model in ['doubao-seedance-2-0','doubao-seedance-2-5','MiniMax-H3','image','doubao-seedream-5.0-lite']:
     with tempfile.TemporaryDirectory(prefix='nmv-provider-freeze-') as tmp:
      base=Path(tmp);reference=base/'reference.jpeg';Image.new('RGB',(64,96),'blue').save(reference)
      audio=base/'voice.wav';audio.write_bytes(b'fixed mocked reference audio')
      calls=[]
      def handle(request):
       calls.append({'method':request.method,'url':str(request.url),'body':json.loads(request.content) if request.content else None})
       if request.url.host=='cdn.invalid':return httpx.Response(200,content=b'fixed generated bytes')
       if request.method=='POST':
        if '/v1/images/generations' in request.url.path:return httpx.Response(200,json={'data':[{'url':'http://cdn.invalid/image.jpeg'}]})
        return httpx.Response(200,json={'task_id':'fixed-task'})
       return httpx.Response(200,json={'data':{'status':'succeeded','url':'http://cdn.invalid/result.mp4','usage':{'tokens':123}}})
      settings=Settings(phanrouter_base_url='http://api.invalid',phanrouter_api_key='test-only',video_model=model,
        image_model='doubao-seedream-5.0-lite' if model.startswith('doubao-seedream') else 'image-test',inline_reference_images=True)
      p=PhanRouterMediaProvider(settings);p.client.close();p.client=httpx.Client(transport=httpx.MockTransport(handle),trust_env=False)
      if model in {'image','doubao-seedream-5.0-lite'}:
       p.create_image('角色画像',base/'image.jpeg',reference=reference)
      else:
       for _ in range(2):p.create_video('角色开门',ImageResult(path=reference,public_url='http://reference.invalid/card.jpeg'),base/'video.mp4',22,reference_audios=(audio,))
      records={f.name:json.loads(f.read_text()) for f in sorted(base.glob('*.json'))}
      results[model]={'requests':calls,'records':records}
      p.client.close()
    return results


def test_requests_resumed_tasks_and_usage_match_previous_provider():
    expected = json.loads((Path(__file__).parent / 'fixtures/provider_services_before.json').read_text())
    assert frozen_providers() == expected


def test_download_can_use_the_h3_direct_client_without_the_generation_client(tmp_path):
    generation_calls, download_calls = [], []
    def wrong(request):
        generation_calls.append(str(request.url))
        raise AssertionError('download went through the generation client')
    def retrieve(request):
        download_calls.append(str(request.url))
        return httpx.Response(200, content=b'existing paid artifact')
    provider = PhanRouterMediaProvider(Settings())
    provider.client.close()
    with httpx.Client(transport=httpx.MockTransport(wrong)) as generation, httpx.Client(transport=httpx.MockTransport(retrieve)) as direct:
        provider.client = generation
        path = tmp_path / 'clip.mp4'
        provider._download('http://internal.invalid/clip', path, client=direct)
    assert not generation_calls and download_calls == ['http://internal.invalid/clip']
    assert path.read_bytes() == b'existing paid artifact'
    assert not path.with_suffix('.mp4.partial').exists()


def test_local_qwen_image_service_draws_the_card_and_writes_it_as_jpeg(tmp_path):
    """The service answers in PNG; a card on disk is .jpeg and must actually be one."""
    import base64, io
    from novel_manga.media.adapters import FramedPhanRouter

    reference = tmp_path / 'style-master.jpeg'
    Image.new('RGB', (64, 64), (10, 20, 30)).save(reference, format='JPEG')
    drawn = io.BytesIO()
    Image.new('RGB', (1152, 2048), (200, 40, 40)).save(drawn, format='PNG')

    requests = []
    def handle(request):
        requests.append(json.loads(request.content))
        return httpx.Response(200, content=drawn.getvalue(), headers={'Content-Type': 'image/png'})

    settings = Settings(local_image_base_url='http://qwen.invalid')
    provider = FramedPhanRouter(settings, {'video_ratio': '9:16', 'text': '竖屏9:16'})
    assert provider.local_image is not None, 'a configured service must be picked up'
    provider.local_image.client.close()
    provider.local_image.client = httpx.Client(transport=httpx.MockTransport(handle), trust_env=False)
    try:
        output = tmp_path / 'turnaround.jpeg'
        result = provider.create_image('一段提示词', output, reference=reference, aspect_ratio='9:16')
    finally:
        provider.client.close()
        provider.local_image.client.close()

    sent, = requests
    assert (sent['width'], sent['height']) == (1080, 1920)
    assert base64.b64decode(sent['references'][0]) == reference.read_bytes()
    assert result.path == output and not output.with_suffix('.jpeg.partial').exists()
    # The service answered 1152x2048 (what the pipeline can draw); the card is what was asked for.
    with Image.open(output) as card:
        assert card.format == 'JPEG' and card.size == (1080, 1920)


def test_a_card_request_records_the_local_model_only_when_one_drew_it(tmp_path):
    """Adding the key unconditionally would make every already-paid-for card look stale
    and archive it on the next run, so the absence is the part worth pinning."""
    from novel_manga.media.asset_images import ensure_image

    class Stub:
        def create_image(self, prompt, output, reference=None, additional_references=(), *, aspect_ratio=None):
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(b'card')
            return ImageResult(path=output)

    hashes = {}
    for label, settings in (('remote', Settings()),
                            ('local', Settings(local_image_base_url='http://qwen.invalid'))):
        output = tmp_path / label / 'turnaround.jpeg'
        ensure_image(settings, Stub(), '一段提示词', output, aspect_ratio='9:16')
        record = json.loads(output.with_suffix('.jpeg.request.json').read_text(encoding='utf-8'))
        hashes[label] = record['request_sha256']
        assert ('local_image_model' in record) == (label == 'local')
    assert hashes['remote'] != hashes['local'], 'switching backend must redraw, not reuse'
